export const RPC_URL = "https://soroban-testnet.stellar.org";
export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";

export const AQUA_CONTRACT_ID =
  "CAYCGEXSUJ2SYV5L3QQS2UOCWQNZ7XK6H70DXAURYCLAE3HPS4SJZUFG";
export const REGISTRY_CONTRACT_ID =
  "CCVABJMB3KN3DVTVJY5FCS5YXMXJKFQYCIRHRRJPQBTFWEDMNFA6P5HV";
